#!/usr/bin/env bash

PLUGIN_DIR="${HOME}/obsidian/.obsidian/plugins"
MJS_FILE="${PWD}/dist/main.mjs"
CJS_FILE="${PWD}/dist/main.js"
STYLES="${PWD}/styles.css"
MANIFEST_FILE="${PWD}/manifest.json"

# dir_exists <filepath>
#
# tests whether a given filepath exists in the filesystem as a directory
function dir_exists() {
    local filepath="${1:?filepath is missing}"

    if [ -d "${filepath}" ]; then
        return 0;
    else
        return 1;
    fi
}

# file_exists <filepath>
#
# tests whether a given filepath exists in the filesystem
function file_exists() {
    local filepath="${1:?filepath is missing}"

    if [ -f "${filepath}" ]; then
        return 0;
    else
        return 1;
    fi
}


# has_command <cmd>
#
# checks whether a particular program passed in via $1 is installed
# on the OS or not (at least within the $PATH)
function has_command() {
    local -r cmd="${1:?cmd not passed into has_command}"

    if command -v "${cmd}" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

function copy_files() {
	if file_exists "${MJS_FILE}"; then
		echo " - converting ESM to CJS using tsup"
		if tsup; then
			echo " - CJS file created locally in dist folder"
		else
			echo " - problem transpiling ESM to CJS!"
			exit 1
		fi

		if file_exists "${CJS_FILE}"; then

			echo " - copying CJS file to plugin directory"
			cp -f "${CJS_FILE}" "${PLUGIN_DIR}/obsidian-kind-model/main.js"

			if file_exists "${MANIFEST_FILE}"; then
				cp -f "${MANIFEST_FILE}" "${PLUGIN_DIR}/obsidian-kind-model"
				echo " - manifest file copied to plugin directory"
			else
				echo " - no manifest file found"
			fi
			if file_exists "${STYLES}"; then
			cp -f "${STYLES}" "${PLUGIN_DIR}/obsidian-kind-model"
			fi
			echo ""

			echo "File Comparison"
			echo "---------------"

			if has_command "exa"; then
				exa -lagh --git "${CJS_FILE}"
				echo ""
				exa -lagh --git "${PLUGIN_DIR}/obsidian-kind-model/main.js"
				exa -lag --git "${PLUGIN_DIR}/obsidian-kind-model/.hotreload"
			elif has_command "eza"; then
				eza -lagh --git "./main.js"
				echo ""
				eza -lagh --git "${PLUGIN_DIR}/obsidian-kind-model/main.js"
				eza -lag --git "${PLUGIN_DIR}/obsidian-kind-model/.hotreload"
			else
				ls -la --color "${PLUGIN_DIR}/obsidian-kind-model/main.js"
			fi

			echo ""

			touch "${PLUGIN_DIR}/obsidian-kind-model/main.js"
			touch "${PLUGIN_DIR}/obsidian-kind-model/.hotreload"
			touch "${PLUGIN_DIR}/obsidian-kind-model/manifest.json"
		else
			echo "- no CJS file found!"
			exit 1;
		fi
	else
		echo "- no MJS source file found from Vite build!"
		touch "${PLUGIN_DIR}/obsidian-kind-model/.hotreload"
	fi
}


echo "Pushing the transpiled JS to Obsidian Vault"
echo "-------------------------------------------"

if dir_exists "${PLUGIN_DIR}/obsidian-kind-model"; then
	copy_files
else
	if dir_exists "${PLUGIN_DIR}"; then
		mkdir "${PLUGIN_DIR}/obsidian-kind-model"
		copy_files
	else
		echo "- for the push functionality to work you must create an 'obsidian' directory"
		echo "  (or symlink) off of your home directory which points to the base of the"
		echo "  vault you'd like to test with"
	fi

fi
